export const Data = [
  {
    name: "Lydia Hallie",
    twitterUrl: "https://twitter.com/lydiahallie",
    githubUrl: "https://github.com/lydiahallie",
    avatarUrl: "https://appjs.co/speakers/lydia.jpg",
    talk: "Modern intro to app development with React and Expo",
    company: "Vercel",
    description:
      "Lydia is hosting Modern intro to app development with React and Expo workshop - please see the description above.",
    id: "0",
    imagePath: "./speakers/lydia.jpg",
  },
  {
    name: "Evan Bacon",
    twitterUrl: "https://twitter.com/Baconrrix",
    githubUrl: "https://github.com/EvanBacon",
    avatarUrl: "https://appjs.co/speakers/evan.jpg",
    talk: "Modern intro to app development with React and Expo",
    company: "Expo",
    description:
      "Evan is hosting Modern intro to app development with React and Expo workshop - please see the description above.",
    id: "1",
    imagePath: "./speakers/evan.jpg",
  },
  {
    name: "Krzysztof Magiera",
    twitterUrl: "https://twitter.com/kzzzf",
    githubUrl: "https://github.com/kmagiera",
    avatarUrl: "https://appjs.co/speakers/krzysztof.jpg",
    talk: "Enriching user experiences with drawings, gestures and animations",
    company: "Software Mansion",
    description:
      "Krzysztof is hosting Enriching user experiences with drawings, gestures and animations workshop - please see the description above.",
    id: "2",
    imagePath: "./speakers/krzysztof.jpg",
  },
  {
    name: "Quinlan Jung",
    twitterUrl: "https://twitter.com/quinlanjung",
    githubUrl: "https://github.com/quinlanj",
    avatarUrl: "https://appjs.co/speakers/quin.jpg",
    talk: "Publish updates with Expo and React Native",
    company: "Expo",
    description:
      "There’s a bug in your app. Fix this by sending a small JS update to your users in between build and submit cycles. Track who got your fix with our Deployments tool. In this talk, I’ll show you how to publish small updates to your users with confidence. We’ll cover how to do this with a production grade app along with more advanced use cases like feature rollouts.",
    id: "3",
    imagePath: "./speakers/quin.jpg",
  },
  {
    name: "William Candillon",
    twitterUrl: "https://twitter.com/wcandillon",
    githubUrl: "https://github.com/wcandillon",
    avatarUrl: "https://appjs.co/speakers/william.jpg",
    talk: "Enriching user experiences with drawings, gestures and animations",
    company: "Can it be done in React Native?",
    description:
      "William is hosting Enriching user experiences with drawings, gestures and animations workshop - please see the description above.",
    id: "4",
    imagePath: "./speakers/william.jpg",
  },
  {
    name: "TC Davis",
    twitterUrl: "https://twitter.com/tc",
    githubUrl: "https://github.com/tcdavis",
    avatarUrl: "https://appjs.co/speakers/tc.jpg",
    talk: "Setting up a professional development process with Expo and EAS",
    company: "Expo",
    description:
      "TC is hosting Setting up a professional development process with Expo and EAS workshop - please see the description above.",
    id: "5",
    imagePath: "./speakers/tc.jpg",
  },
  {
    name: "Kelvin Okundi Ndemo",
    twitterUrl: "https://twitter.com/NdemoKelvin",
    githubUrl: "https://github.com/kelvinndmo",
    avatarUrl: "https://appjs.co/speakers/kelvin.jpg",
    talk: "Expo at scale in fast paced startup; Build, Deploy, Publish",
    company: "Twiga Foods",
    description:
      "In this talk, I want to focus on how Expo has made it easy for us as a company to build two apps we are maintaining and deploy them with ease, how we are able to fix and publish code within seconds and how EAS has boosted our productivity. Not being a native developer, and having tried maintaining two codebases as a startup with only 3 engineers, my talk will be focused on how the build once deploy everywhere philosophy has really benefited us as a company and the flexibility that expo offers to us.",
    id: "6",
    imagePath: "./speakers/kelvin.jpg",
  },
  {
    name: "Jon Samp",
    twitterUrl: "https://twitter.com/JonSamp",
    githubUrl: "https://github.com/jonsamp",
    avatarUrl: "https://appjs.co/speakers/jon.jpg",
    talk: "Setting up a professional development process with Expo and EAS",
    company: "Expo",
    description:
      "Jon is hosting Setting up a professional development process with Expo and EAS workshop - please see the description above.",
    id: "7",
    imagePath: "./speakers/jon.jpg",
  },
  {
    name: "Monica Restrepo",
    twitterUrl: "https://twitter.com/ImRestrepo",
    githubUrl: "https://github.com/iamrestrepo",
    avatarUrl: "https://appjs.co/speakers/monica.jpg",
    talk: "Building for all and for us: how contributing to open source projects is helping Shopify and React Native build the future of Mobile.",
    company: "Shopify",
    description:
      "One of the most  important features of React Native is the community support to the framework and the multiple libraries built around its ecosystem. React Native's transformation  of mobile development has only been so successful due to the multiple parties constantly investing in its evolution.  This talk aims to provide some insights into Shopify's mission to improve React Native by addressing the framework's biggest shortcomings.",
    id: "8",
    imagePath: "./speakers/monica.jpg",
  },
  {
    name: "Axel Delafosse",
    twitterUrl: "https://twitter.com/axeldelafosse",
    githubUrl: "https://github.com/axeldelafosse",
    avatarUrl: "https://appjs.co/speakers/axel.jpg",
    talk: "How to build a universal design system",
    company: "Showtime",
    description:
      "How do you build a design system that works on React DOM and React Native, with a familiar styling solution that can be shared across multiple apps and used by multiple teams? This is something we solved while building the Showtime app. We created Universal UI: a universal design system that works on iOS, Android and Web. It's a library of high-quality components to build your apps faster with less code (and less bugs). Come to App.js to learn how to build your own universal design system based on Universal UI!",
    id: "9",
    imagePath: "./speakers/axel.jpg",
  },
  {
    name: "Derek Stavis",
    twitterUrl: "https://twitter.com/derekstavis",
    githubUrl: "https://github.com/derekstavis",
    avatarUrl: "https://appjs.co/speakers/derek.jpg",
    talk: "Controlling hardware in a week with Expo and EAS",
    company: "Brex",
    description:
      "I love my e-bike but I felt like none of the apps available to configure and track rides were up to my standards. That’s why I decided to build my own. But if working with hardware by itself isn’t already hard, creating a smooth user experience, dealing with the build and distribution process makes everything more complicated. That is, unless you use Expo, Reanimated2 and EAS. During this talk I’m going to share how I went from idea to creating a Bluetooth LE enabled app, an amazing animated dashboard and a great user experience using these tools in 1 week.",
    id: "10",
    imagePath: "./speakers/derek.jpg",
  },
  {
    name: "Kudo Chien",
    twitterUrl: "https://twitter.com/kudochien",
    githubUrl: "https://github.com/kudo",
    avatarUrl: "https://appjs.co/speakers/kudo.jpg",
    talk: "The Hidden Features from V8 to Boost Your React Native Apps",
    company: "Expo",
    description:
      "Benefiting from JSI abstraction, nowadays, we can have different JavaScript runtimes by developers' choices. Many references recommend using Hermes for TTI (Time-To-Interactive) performance gain. On the other hand, V8, another famous JavaScript runtime you probably would use daily from Google Chrome or Microsoft Edge browsers, has many powerful features. This talk would go through some V8 features like JIT, inspector, WebAssembly, and bytecode caching to help React Native apps. These weapons will give developers more choices to develop good apps. Other than that, with Expo config-plugins, V8 adoption in an Expo managed project has never been easier.",
    id: "11",
    imagePath: "./speakers/kudo.jpg",
  },
  {
    name: "Fernando Rojo",
    twitterUrl: "https://twitter.com/fernandotherojo",
    githubUrl: "https://github.com/nandorojo",
    avatarUrl: "https://appjs.co/speakers/fernando.jpg",
    talk: "Building Cross-Platform Apps with React Native + Next.js",
    company: "BeatGig",
    description:
      "One of the main benefits of using React Native for us has been the ability to share non-UI code between our web applications and our mobile applications. This talk, Fernando will focus on  how to properly setup a monorepo with shared code and React/React Native apps and how to build and deployment configurations for Expo, Vercel, etc.. He will also cover architecture choices, authentication flows (same backend API but very different frontend) and common problems and some other issues we've encountered.",
    id: "12",
    imagePath: "./speakers/fernando.jpg",
  },
  {
    name: "Vanya Deasy Safrina",
    twitterUrl: "https://twitter.com/vanydeasy",
    githubUrl: "https://github.com/vanydeasy",
    avatarUrl: "https://appjs.co/speakers/vanya.jpg",
    talk: "React Native at Traveloka",
    company: "Traveloka",
    description:
      "The speech will revolve around our journey using React Native to develop applications at Traveloka. Currently, we have 1 hybrid application and 6 applications built using React Native from scratch. Reusability is the key theme of our work, so I will focus on the interoperability between React Native and Native which includes git submodules to support development workflow in multiple repositories and sharing components between them. I will also talk about how we developed an in-house solution for enabling bundle splitting in React Native code as it enables several capabilities, such as Independent CodePush release.",
    id: "13",
    imagePath: "./speakers/vanya.jpg",
  },
  {
    name: "Catalin Miron",
    twitterUrl: "https://twitter.com/mironcatalin",
    githubUrl: "https://github.com/catalinmiron",
    avatarUrl: "https://appjs.co/speakers/catalin.jpg",
    talk: "Animations should be fun",
    company: "Nomad Developer",
    description:
      "Are you afraid of animations? Well, you shouldn't be, Reanimated got you covered. Your mobile application can share a story through animations, can help users through micro-interactions and differentiate your app from the others.",
    id: "14",
    imagePath: "./speakers/catalin.jpg",
  },
  {
    name: "Jessica Lo",
    avatarUrl: "https://appjs.co/speakers/jessica.jpg",
    talk: "Scaling the mobile app",
    company: "Chime",
    description:
      "At Chime, we need to ensure our mobile app can scale with our member base. There are a number of intentional design decisions we’ve made to ensure our members’ experience is seamless and our app is both highly available and resilient. In the talk, we will cover topics of REST/GraphQL requests, designing our mobile queries, and keeping our app resilient.",
    id: "15",
    imagePath: "./speakers/jessica.jpg",
  },
  {
    name: "Wouter van der Broek",
    twitterUrl: "https://twitter.com/wbroek",
    githubUrl: "https://github.com/wbroek",
    avatarUrl: "https://appjs.co/speakers/wouter.jpg",
    talk: "Infiltrate your own Expo / React Native app",
    company: "Synappz Digital Health",
    description:
      "Wouter van den Broek is a independent consultant and engineer.  He has build more than 200 apps, from Symbian to BlackBerry to iOS and Android and now on the endeavor with React Native. With all these years of experience in the mobile world with building mobile apps there is alot of knowledge to be shared. Also loves new technology, software processes; how to figure those out and traveling and reading.",
    id: "16",
    imagePath: "./speakers/wouter.jpg",
  },
  {
    name: "Jude Ganihu",
    twitterUrl: "https://twitter.com/kpoosee",
    githubUrl: null,
    avatarUrl: "https://appjs.co/speakers/jude.jpg",
    talk: "Securely Processing Payments in React Native apps",
    company: "Flutterwave",
    description:
      "Ever wondered how hackers can compromise your app and your app data? In this talk you will see in a live demo on stage how to infiltrate an app with different techniques like decompiling, sniffing and reverse enginering. By the end of the talk, you'll walk away a little bit scared but more prepared with some great practices to infiltrate your own app and the knowledge to battle them.",
    id: "17",
    imagePath: "./speakers/jude.jpg",
  },
  {
    name: "Kadi Kraman",
    twitterUrl: "https://twitter.com/kadikraman",
    githubUrl: "https://github.com/kadikraman",
    avatarUrl: "https://appjs.co/speakers/kadi.jpg",
    talk: "Building a 5 star app",
    company: "Formidable Labs",
    description:
      "Users can rate mobile apps, and that is both a blessing and a curse. On the one hand: you can get direct user feedback that can help you improve the app! On the other hand, you may get direct user feedback on things you have zero control over. In this talk we explore how to leverage tech, UX and psychology to enhance your app and give it the best possible chance of reaching a top rating.",
    id: "18",
    imagePath: "./speakers/kadi.jpg",
  },
  {
    name: "Alexandre Moureaux",
    twitterUrl: "https://twitter.com/almouro",
    githubUrl: "https://github.com/almouro",
    avatarUrl: "https://appjs.co/speakers/alexandre.jpg",
    talk: "Measuring and improve React Native performance",
    company: "BAM",
    description:
      "The web has several tools to measure performance, but what about us, React Native devs? Have you ever added some optimization in your code (like a memo here and there) and wondered if it had a real impact on performance? Presenting a Flipper plugin to measure React Native performance, with a concrete case of how we used it to bring our app performance to the top quality. Bonus: a deep dive into React DevTools flame charts!",
    id: "19",
    imagePath: "./speakers/alexandre.jpg",
  },
  {
    name: "Sanket Sahu",
    twitterUrl: "https://twitter.com/sanketsahu",
    githubUrl: "https://github.com/sanketsahu",
    avatarUrl: "https://appjs.co/speakers/sanket.jpg",
    talk: "The state of one codebase for all the platforms",
    company: "GeekyAnts",
    description:
      "How can we have one codebase for mobile and web when both of them have different APIs and behaviour? In the talk, I will cover the behavioural and the technical differences for web and mobile platforms. From a behavioural point of view, what are the different ways that users interact with the interfaces, covering right from gestures for navigation to how accessibility is handled. From a technical point of view, I will talk about the high-level architecture from painting pixels on the screen to the React Native and React source codes. After setting up the stage for differences, I will present ideas on how the community is solving them and what's the current state of the same. This includes talking about Expo, React Native Web, Accessibility and a unified Navigation approach.",
    id: "20",
    imagePath: "./speakers/sanket.jpg",
  },
  {
    name: "Sean Han",
    twitterUrl: "https://twitter.com/0xs34n",
    githubUrl: "https://github.com/0xs34n",
    avatarUrl: "https://appjs.co/speakers/sean.jpg",
    talk: "Web3 for Mass Adoption with StarkNet and React Native",
    company: "PlayOasis",
    description:
      "Why do we need the blockchain? For the first time ever, blockchain allows people to own a piece of digital asset on the internet. Digital ownership and sovereignty has unlocked new use cases that allows people to create, trade, and earn value online with unprecedented scale. With StarkNet.js, you can now build scalable web3 mobile dApps that allow your users to participate in this new digital economy.",
    id: "21",
    imagePath: "./speakers/sean.jpg",
  },
  {
    name: "Janek Rahrt",
    twitterUrl: "https://twitter.com/0xjanek",
    githubUrl: null,
    avatarUrl: "https://appjs.co/speakers/janek.jpg",
    talk: "Web3 for Mass Adoption with StarkNet and React Native",
    company: "Argent",
    description:
      "Why do we need the blockchain? For the first time ever, blockchain allows people to own a piece of digital asset on the internet. Digital ownership and sovereignty has unlocked new use cases that allows people to create, trade, and earn value online with unprecedented scale. With StarkNet.js, you can now build scalable web3 mobile dApps that allow your users to participate in this new digital economy.",
    id: "22",
    imagePath: "./speakers/janek.jpg",
  },
  {
    name: "Tomasz Zawadzki",
    twitterUrl: "https://twitter.com/tomekzaw",
    githubUrl: "https://github.com/piaskowyk",
    avatarUrl: "https://appjs.co/speakers/tomek.jpg",
    talk: "Everything you need to know about Fabric and JSI",
    company: "Software Mansion",
    description:
      "Tomasz is hosting Everything you need to know about Fabric and JSI workshop - please see the description above.",
    id: "23",
    imagePath: "./speakers/tomek.jpg",
  },
  {
    name: "Magdalena Jaśkowska",
    twitterUrl: null,
    githubUrl: "https://github.com/mjaskowska",
    avatarUrl: "https://appjs.co/speakers/magdalena.jpg",
    talk: "The only in-app notification library that you will ever need.",
    company: "The Widlarz Group",
    description:
      "Have you ever had a problem with creating in-app notifications for your users? None of the available solutions meet your expectations? Let me introduce the brand new in-app notification library. I’ll demonstrate its features and how to implement it into your code. Customise animations, styles and more or choose from the wide range of options we have prepared.",
    id: "24",
    imagePath: "./speakers/magdalena.jpg",
  },
  {
    name: "Nicola Corti",
    twitterUrl: "https://twitter.com/cortinico",
    githubUrl: "https://github.com/cortinico",
    avatarUrl: "https://appjs.co/speakers/nicola.jpg",
    talk: "Bringing the New React Native Architecture to the OSS community",
    company: "Meta",
    description:
      "At the end of 2021, Meta successfully rolled out the new React Native architecture in the Facebook app. Now, it’s time to empower every React Native developer on the globe to use it. To support the whole community in this endeavor, we lined up a set of tools and materials that will help both app and library developers to join us in this journey. In the talk, I will present how the New React Native Architecture looks in the OSS space. I will discuss the impact this will have on developing React Native projects. Lastly, I will cover what we learned from the React Native new architecture migration at Meta, and how you can tackle your migration in your organization.",
    id: "25",
    imagePath: "./speakers/nicola.jpg",
  },
  {
    name: "George Xu",
    avatarUrl: "https://appjs.co/speakers/george.jpg",
    talk: "Scaling the mobile app",
    company: "Chime",
    description:
      "At Chime, we need to ensure our mobile app can scale with our member base. There are a number of intentional design decisions we’ve made to ensure our members’ experience is seamless and our app is both highly available and resilient. In the talk, we will cover topics of REST/GraphQL requests, designing our mobile queries, and keeping our app resilient.",
    id: "26",
    imagePath: "./speakers/george.jpg",
  },
  {
    name: "Michał Pierzchała",
    twitterUrl: "https://twitter.com/thymikee",
    githubUrl: "https://github.com/thymikee",
    avatarUrl: "https://appjs.co/speakers/michal.jpg",
    talk: "Continuous monitoring app's performance, made simple",
    company: "Callstack",
    description:
      "A wise person once said: “Never spend 6 minutes doing something by hand when you can spend 6 hours failing to automate it”. As developers we love automating things. It’s not always simple though. It’s not always possible yet as well. We can’t be sure if we don’t try at least. When it comes to performance testing of React and React Native applications, we usually pick the manual way, because the topic quite complex with issues coming from multiple realms. But what if we could automate some part of it? Make measuring the most impacting metrics a habit? Let’s say, a part of the standard CI pipeline? Wouldn't we spot the issues quicker this way? Look no more, because someone already spend those “6 hours” for you and is going to open source it really soon.",
    id: "27",
    imagePath: "./speakers/michal.jpg",
  },
  {
    name: "Mateusz Front",
    twitterUrl: "https://twitter.com/uusszz",
    githubUrl: "https://github.com/mat-hek",
    avatarUrl: "https://appjs.co/speakers/mateusz.jpg",
    talk: "Using your phone to make an actual call - videoconferencing in React Native with Membrane",
    company: "Software Mansion",
    description:
      "In case you forgot, making calls was the initial reason behind inventing the telephone. Nowadays, video calling is no big deal too, so it should be fairly easy to embed a video calling feature in your app, right? Well, it wasn't until we created Membrane-RN-WebRTC. In this talk, I'll show you how to set up video chat in your RN app in minutes, with Membrane RTC Engine [https://github.com/membraneframework/membrane_rtc_engine] working as the media server. I'll also explain what technologies we used and why, why video streaming is hard in general and what Membrane-RN-WebRTC does to make it easier.",
    id: "28",
    imagePath: "./speakers/mateusz.jpg",
  },
];

/** Given an ID, returns a speaker from App.js conf 2022 */
export function getUser(id) {
  return Data.find((user) => user.id === id)!;
}
